stages:
  - deploy

deploy_image:
  stage: deploy
  tags:
    - docker
  script:
    - docker build -t registry.anspar.io/hosq:latest .
    - docker login -u "$DOCKER_L" -p "$DOCKER_P" registry.anspar.io
    - docker push registry.anspar.io/hosq:latest